version: "3.8"

services:
  php-DEV:
    depends_on:
      - mysql-DEV
    container_name: site-grenier-DEV
    build:
      context: .
      dockerfile: Dockerfile
    image: my-vide-grenier
    ports:
      - 90:80
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - netbdd
  mysql-DEV:
    container_name: mysql-DEV
    restart: always
    image: mysql:5.7.41
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
    volumes:
      - ./sql/import.sql:/docker-entrypoint-initdb.d/datadump.sql
    networks:
      - netbdd
networks:
  netbdd:
volumes:
  vendor:
