version: "3.8"

services:
  php-Rel-Beta-1:
    depends_on:
      - mysql-Rel-Beta-1
    container_name: site-grenier-Rel-Beta-1
    build:
      context: .
      dockerfile: Dockerfile_Rel
    image: my-vide-grenier_rel-beta-1
    ports:
      - 90:80
    networks:
      - netbdd
    volumes:
      - ../../my-apache.conf:/etc/apache2/sites-available/000-default.conf
  mysql-Rel-Beta-1:
    container_name: mysql-Rel-Beta-1
    restart: always
    image: mysql:5.7.41
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
    volumes:
      - ../../sql/import.sql:/docker-entrypoint-initdb.d/datadump.sql
    networks:
      - netbdd
networks:
  netbdd:
