version: "3.8"

services:
  php-DEV:
    depends_on:
      - mysql-DEV
    container_name: site-grenier-DEV
    build:
      context: ../../
      dockerfile: ./install/develop/Dockerfile
    image: my-vide-grenier_dev
    ports:
      - 90:80
    volumes:
      - ../my-apache.conf:/etc/apache2/sites-available/000-default.conf
      - ../uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ../../.:/var/www/html
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    networks:
      - netbdd_dev
  mysql-DEV:
    container_name: mysql-DEV
    restart: always
    image: mysql:5.7.41
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
    volumes:
      - ../../sql/import.sql:/docker-entrypoint-initdb.d/datadump.sql
      - ../my.cnf:/etc/my.cnf
      - bdd_DEV:/var/lib/mysql
    networks:
      - netbdd_dev
networks:
  netbdd_dev:
volumes:
  vendor:
  node_modules:
  bdd_DEV:
