version: "3.8"

services:
  php-Prod:
    depends_on:
      - mysql-Prod
    container_name: site-grenier-Prod
    build:
      context: .
      dockerfile: Dockerfile
    image: my-vide-grenier_prod:prod
    ports:
      - 92:80
    networks:
      - netbdd_prod
    volumes:
      - ../my-apache.conf:/etc/apache2/sites-available/000-default.conf
      - ../uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  mysql-Prod:
    container_name: mysql-Prod
    restart: always
    image: mysql:5.7.41
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
    volumes:
      - ../../sql/import.sql:/docker-entrypoint-initdb.d/datadump.sql
      - ../my.cnf:/etc/my.cnf
      - bdd_PROD:/var/lib/mysql
    networks:
      - netbdd_prod
networks:
  netbdd_prod:
volumes:
  bdd_PROD:
